### ISSUE TITLE
nosetests: error: no such option: --noselog-format

### ISSUE THREAD

**Issue by swatisharma023** [vmalloc/noselog#2]
I am trying to run noselog using this command:

nosetests -s -v Test_cases\test_calculator.py --with-noselog --noselog-file=github.log --noselog-format="%(asctime)s %(name)s  -- %(message)s"

I am getting this error:

nosetests: error: no such option: --noselog-format

**Comment by vmalloc** [comment]
@swatisharma023 this package is no longer maintained. I strongly recommend moving away from nose into more modern, better maintained testing tools.

**Comment by swatisharma023** [comment]
Can you please suggest new testing tools to use with python and selenium. I search on google, all it display is nose or pytest. Thanks.

**Comment by vmalloc** [comment]
@swatisharma023 pytest is pretty great. It has a plugin called pytest-selenium which is fairly convenient to work with.
